#pragma once

#define _VOB_MISTD_STRINGIZE(N) #N
#define _VOB_MISTD_APPLY(M, L) M(L)
#define _VOB_MISTD_LINE_STRING _VOB_MISTD_APPLY(_VOB_MISTD_STRINGIZE, __LINE__)
#define _VOB_MISTD_MESSAGE(type) __FILE__ "(" _VOB_MISTD_LINE_STRING "): " #type " : "
#define VOB_MISTD_TODO _VOB_MISTD_MESSAGE(TODO)
#define VOB_MISTD_HACK _VOB_MISTD_MESSAGE(HACK)
